### ISSUE TITLE
Log in Issue

### ISSUE THREAD

**Issue by theshiv1337** [merces/aleph#71]
Not sure if anyone will see this since this project hasn't been active in a while...

I setup Aleph and everything seems to be fine but I cannot log into the web interface. The screen reloads and nothing happens. Not sure if its my config or what. I tried chmoding all files in webui but still having the issue.

**Comment by jseidl** [comment]
Hi,

Hard to have an idea without more information. Can you supply the logs?

Have you set the SECRET_KEY parameter in the settings file?

**Comment by theshiv1337** [comment]
My apologies, I did some testing. Apparently my config is fine but there is some sort of incompatibility with Google Chrome. I was able to login just fine using Firefox.
